- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleVoidwalker
  name: Voidwalker Role
  components:
  - type: MindRole
    antagPrototype: Voidwalker
    roleType: FreeAgent # Maybe this should be solo antag?
    subtype: role-subtype-voidwalker
    exclusiveAntag: true
  - type: VoidwalkerRole
