- type: entity
  parent: BaseMindRoleAntag
  id: VoltLeechMindRole
  name: Volt Leech Role
  components:
  - type: MindRole
    antagPrototype: VoltLeech
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-volt-leech
  - type: VoltLeechRole
